import Head from 'next/head';
import Header from '../components/Header';
import Nav from '../components/Nav';
import Results from '../components/Results';
import requestedAPI from './utils/requests';

export default function Home({result}) {
  return (
    <div>
      <Head>
        <title>Hulu </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Nav />
      <Results data={result}  />
    </div>
  )
}

export async function getServerSideProps(context) {
  const genre = context.query.genre;
  const request = await fetch(`https://api.themoviedb.org/3${
    requestedAPI.genre?.url || requestedAPI.fetchTrending.url
    }`).then(response => response.json())
  return {
    props: {
      result: request.results
    }, // will be passed to the page component as props
  }
}