import Head from 'next/head';
import Header from '../components/Header';
import Nav from '../components/Nav';

export default function Home() {
  console.log('API clg : ', process.env.API_KEY);
  return (
    <div>
      <Head>
        <title>Hulu </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Nav />
    </div>
  )
}

export async function getServerSideProps(context) {
  const genre = context.query.genre;
  console.log(context.query);
  return {
    props: {}, // will be passed to the page component as props
  }
}